#!/bin/env bash

# shellcheck source=/dev/null
source /etc/profile.d/instance.sh 2>/dev/null
: "${PATHINSTANCE:?Please set \$PATHINSTANCE env variable!}"

MSG=$(echo "$1" | awk '
/202[0-9]-/ {
    if (/nginx:/) { split($0,a,"\""); print "<pre>"a[2]"\n"a[4]"\n"a[6]"</pre>"; next }
    if (/sshd/)   { sub(/^.*]: /,""); print "<pre>"$0; next }
}1')

[ -f "$PATHINSTANCE"/scripts/tgsay.sh ] && "$PATHINSTANCE"/scripts/tgsay.sh "$MSG"
