#!/bin/env bash
# shellcheck disable=1091

# shellcheck source=/dev/null
source /etc/profile.d/instance.sh 2>/dev/null
: "${PATHINSTANCE:?Please set \$PATHINSTANCE env variable!}"

config=$HOME/.config/newrelease

function print_help {
    underline=$(tput smul)
    nounderline=$(tput rmul)
    echo "
New release watchdog from git sources.

${underline}Usage${nounderline}: ${0##*/} [OPTIONS]

${underline}Options${nounderline}:
  [-a <giturl>] Add new git source for watchdog
  [-e]          Edit main list/config
  [-t]          Edit exclide tags list
"
}

function addgitpath {
    mkdir -p "$config"
    pkgfolder=$(basename "$1" ".git")
    case $1 in
    *gitlab*) releases="/-/releases/" ;;
    *) releases="/releases/tag/" ;;
    esac
    echo "$pkgfolder $1 $releases init" >>"$config/gitlist"
    sort -uo "$config/gitlist"{,}
}

while getopts ':ha:et' option; do
    case "$option" in
    h)
        print_help
        exit 0
        ;;
    a) addgitpath "$OPTARG" ;;
    e)
        [ -n "$EDITOR" ] && $EDITOR "$config/gitlist" || echo "Please set \$EDITOR variable first!"
        exit 0
        ;;
    t)
        [ -n "$EDITOR" ] && $EDITOR "$config/exclude.tags" || echo "Please set \$EDITOR variable first!"
        exit 0
        ;;
    \?) [ -n "$OPTARG" ] && { echo "Option not found, try -h" && exit 1; } ;;
    esac
done
shift $((OPTIND - 1))

cp "$config/gitlist" "/tmp/gitlist"
[ -f "$config/exclude.tags" ] || printf "# Set tags (or part of) that need to be pass from watching, one in line\n# Comments and empty lines are allowed\n\n" > "$config/exclude.tags"

while read -r string; do
    IFS=" " read -r -a git <<<"$string"
    if ! tags=$(git -c 'versionsort.suffix=+' -c 'versionsort.suffix=-' ls-remote --refs --tags "${git[1]}" 2>/dev/null); then
        continue
    else
        remotetag=$(echo "$tags" | \
            awk '{sub("refs/tags/", "", $2); tag=$2; sub(/^v/, "", tag); print tag, $2}' | \
            grep -Ev -f <(grep -Ev '^\s*$|^\s*#' "$config/exclude.tags") | \
            sort -k1 -V | awk 'END {print $2}')
    fi
    [ "$remotetag" == "" ] && remotetag="notagsyet"
    if [ "${git[3]}" != "$remotetag" ]; then
        rel=$([ "${git[3]}" != "init" ] && echo "New" || echo "Init")
        viewurl=""
        [ "$remotetag" != "notagsyet" ] && viewurl="
${git[1]/\.git/}${git[2]}$remotetag"
        [ -f "$PATHINSTANCE"/scripts/tgsay.sh ] && "$PATHINSTANCE"/scripts/tgsay.sh "$rel release <u>${git[0]}</u> - <b>${git[3]} -> $remotetag</b>$viewurl" false
        sed -i "/${git[0]}/d" /tmp/gitlist
        echo "${git[0]} ${git[1]} ${git[2]} $remotetag" >>/tmp/gitlist
    fi
done <"$config/gitlist"

if cmp -s "/tmp/gitlist" "$config/gitlist"; then
    rm "/tmp/gitlist"
else
    mv "/tmp/gitlist" "$config/gitlist"
fi
