#!/bin/bash
#shellcheck disable=1091

config=$HOME/.config/newrelease

[ -z "$PATHINSTANCE" ] && source /etc/profile.d/instance.sh
[ -z "$PATHINSTANCE" ] && { echo "Please set \$PATHINSTANCE env variable!"; exit 1; }

function print_help {
    underline=$(tput smul)
    nounderline=$(tput rmul)
    echo "
New release watchdog from git sources.

${underline}Usage${nounderline}: ${0##*/} [OPTIONS]

${underline}Options${nounderline}:
  [-a <giturl>] Add new git source for watchdog
  [-e]          Edit main list/config
"
}

function addgitpath {
    mkdir -p "$config"
    pkgfolder=$(basename "$1" ".git" )
    echo "$1 $pkgfolder /releases/tag/ init" >> "$config/gitlist"
    sort -uo "$config/gitlist"{,}
}

while getopts ':ha:e' option; do
    case "$option" in
         h ) print_help; exit 0;;
         a ) addgitpath "$OPTARG";;
         e ) [ -n "$EDITOR" ] && $EDITOR "$config/gitlist" || echo "Please set \$EDITOR variable first!"; exit 0;;
        \? ) [ -n "$OPTARG" ] && { echo "Option not found, try -h" && exit 1; }
    esac
done
shift $((OPTIND - 1))

cp "$config/gitlist" "/tmp/gitlist"

while read -r string
do
    IFS=" " read -r -a git <<< "$string"
    remotetag=$(git -c 'versionsort.suffix=+' -c 'versionsort.suffix=-' ls-remote --refs --sort='-v:refname' --tags "${git[0]}" | head -1 | cut -d/ -f3)
    [ "$remotetag" == "" ] && remotetag="notagsyet"
    if [ "${git[3]}" != "$remotetag" ]
    then
        rel=$([ "${git[3]}" != "init" ] && echo "New" || echo "Init")
        [ "$remotetag" != "notagsyet" ] && viewurl="
${git[0]/\.git/}${git[2]}$remotetag"
        [ -f "$PATHINSTANCE"/scripts/tgsay.sh ] && "$PATHINSTANCE"/scripts/tgsay.sh "$rel release <u>${git[1]}</u> - <b>${git[3]} -> $remotetag</b>$viewurl"
        sed -i "/${git[1]}/d" /tmp/gitlist
        echo "${git[0]} ${git[1]} ${git[2]} $remotetag" >> /tmp/gitlist
    fi
done < "$config/gitlist"

if cmp -s "/tmp/gitlist" "$config/gitlist"
then
    rm "/tmp/gitlist"
else
    mv "/tmp/gitlist" "$config/gitlist"
fi
