#!/bin/bash

function client_daily ()
{
	reload=1;
	ADDTRD=0; ADDTRX=0;
	MINTRX=0; MAXTRX=0;
	MINTRD=0; MAXTRD=0;
	OLDIFS=$IFS; IFS=$'\n';
	for LINE in $(grep $1" " $LOGSDIR/$2*.log)
	do
		IFS=$OLDIFS
		declare -a arr=($LINE)
		if [ ${arr[2]} -lt 3600 ]
		then
			let "ADDTRD = ADDTRD + MAXTRD - MINTRD + ${arr[5]}"
			let "ADDTRX = ADDTRX + MAXTRX - MINTRX + ${arr[6]}"
			reload=1
		fi
		[ $reload -eq 1 ] && { MINTRX=${arr[5]}; MINTRD=${arr[6]}; reload=0; }
		MAXTRX=${arr[5]}; MAXTRD=${arr[6]};
	done
	let "TRDD = ADDTRD +  MAXTRD - MINTRD"
	let "TRXD = ADDTRX +  MAXTRX - MINTRX"
}


LOGDIR="/var/log/wgstat"
CLIENTS=$(awk '/###/,/AllowedIPs =/' /etc/wireguard/wg0.conf | grep -E "(###|AllowedIPs)" | sed 's/### Client //;s/AllowedIPs = //' | tr '\n' '|' | sed 's/|10/ 10/g')
DATE=$(date -d '1 hour ago' +"%F")
HOUR=$(date -d '1 hour ago' +"%H")
UPTIME=$(cut -d"." -f1 /proc/uptime)
NOW=$(date +"%F")

mkdir -p $LOGDIR
LOGFILE="$LOGDIR/$DATE-$HOUR.log"
echo -n > $LOGFILE

wg show all dump | awk 'FNR>1 {print $5,$7,$8}' | sort -V | while read stat_line
do
    name_client=$(echo $CLIENTS | tr '|' '\n' | grep "$(echo $stat_line | cut -d" " -f1)" | cut -d" " -f1)
    echo $DATE" "$HOUR" "$UPTIME" "$name_client" "$stat_line >> $LOGFILE  
done

if [ "$NOW" != "$DATE" ]
then
	LOGFILEDAY="$LOGDIR/$DATE-24.log"
	echo  -n > $LOGFILEDAY
	for CLIENT in $(cat $LOGDIR/$DATE*.log | cut -d" " -f4 | sort -u)
	do
		client_daily $CLIENT $DATE
		ip=$(cat $LOGDIR/$DATE*.log | grep "$CLIENT " | cut -d" " -f5 | sort -u)
		echo "$DATE 24 0 $CLIENT $ip $TRXD $TRDD" >> $LOGFILEDAY
	done
	rm $(ls $LOGDIR/$DATE*.log | grep -v "\-24.log")
fi
